second

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,18 +1,11 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir>
 
-# fail fast
 set -e
+set -o pipefail
 
-# debug
-# set -x
-
-shopt -s extglob
-
-function error() {
-  echo " !     $*" >&2
-  exit 1
-}
+BUILD_DIR=$1
+CACHE_DIR=$2
 
 function indent() {
   c='s/^/       /'
@@ -22,85 +15,51 @@ function indent() {
   esac
 }
 
-# clean up leaking environment
-unset GIT_DIR
+BIN_DIR=$(cd $(dirname $0); pwd) # absolute path
+OPT_DIR=$(cd "$BIN_DIR/../usr"; pwd)
 
-# parse and derive params
-BUILD_DIR=$1
-CACHE_DIR="$2/vendor"
-LP_DIR=`cd $(dirname $0); cd ..; pwd`
-BUILDPACK_DIR="$(dirname $(dirname $0))"
+LUA=vlc
 
-# config
-R_VERSION="3.1.0"
-BUILD_PACK_VERSION="20140608-1824"
+cd $BUILD_DIR
 
-S3_BUCKET="heroku-buildpack-r"
-R_BINARIES="http://${S3_BUCKET}.s3.amazonaws.com/R-${R_VERSION}-binaries-${BUILD_PACK_VERSION}.tar.gz"
+mkdir -p bin
+#mkdir -p packages
+mkdir -p etc
+mkdir -p usr
+mkdir -p lib
+mkdir -p share
+mkdir -p usr/share
 
-VENDOR_DIR="$BUILD_DIR/vendor"
-R_BASE="$VENDOR_DIR/R"
-CRAN_MIRROR="http://cran.revolutionanalytics.com"
+echo "-----> Copying vlc to bin"
+cp "$OPT_DIR/vlc" "bin/"
 
-mkdir -p $CACHE_DIR
+echo "-----> Installing packages"
 
-# vendor R into the slug
-echo "Vendoring R $R_VERSION" | indent
+#SITE_CONFIG="$OPT_DIR/luarocks/luarocks/site_config.lua"
 
-# download and unpack binaries
-echo "Downloading and unpacking R binaries" | indent
-mkdir -p $VENDOR_DIR && curl $R_BINARIES -s -o - | tar xzf - -C $VENDOR_DIR
+if [ "$ENV" != "local" ]; then
+	cp "$OPT_DIR/lib" " /lib/"
+	cp "$OPT_DIR/share" " /usr/share"
+  #export PATH=$OPT_DIR/$STACK:$PATH
+  #echo "site_config.LUA_INCDIR=[[$OPT_DIR/../include]]" >> $SITE_CONFIG
+  #echo "site_config.LUA_LIBDIR=[[$OPT_DIR/../lib/$STACK/]]" >> $SITE_CONFIG
+else
+  LUA=vlc
+fi
 
-# need to copy the binaries to /app/vendor so that R works
-mkdir -p /app/vendor/gcc
-cp -R $VENDOR_DIR/gcc/* /app/vendor/gcc
+# # use sed because grep halts script with -e when there is no match
+# ROCKSPEC=$(ls | sed -n 's/\.rockspec$/&/p' | head -n 1)
+#
+# if [[ -z "$ROCKSPEC" ]]; then
+#   echo "-----> Fatal Error"
+#   echo ""
+#   echo "       package.lua is no longer supported."
+#   echo ""
+#   echo "       You must provide a rockspec with your app."
+#   echo "       See https://github.com/leafo/heroku-buildpack-lua/blob/master/README.md"
+#   echo ""
+#   exit 1
+# fi
 
-mkdir -p /app/vendor/glibc
-cp -R $VENDOR_DIR/glibc/* /app/vendor/glibc
+# $LUA "$OPT_DIR/prepare.lua" $ROCKSPEC $OPT_DIR 2>&1 | indent
 
-mkdir -p /app/vendor/gsl
-cp -R $VENDOR_DIR/gsl/* /app/vendor/gsl
-
-mkdir -p /app/vendor/R
-cp -R $VENDOR_DIR/R/* /app/vendor/R
-
-# HACK: need to copy over the gcc libs so that packages can find them
-mkdir -p /app/vendor/R/lib64/R/lib
-cp /app/vendor/gcc/lib64/* /app/vendor/R/lib64/R/lib
-
-# R needs to know where gfortran and glibc header files are
-export PATH="/app/vendor/R/bin:/app/vendor/gcc/bin:$PATH"
-
-export LDFLAGS="-L/app/vendor/gcc/lib64 -L/app/vendor/gsl/lib"
-export CPPFLAGS="-I/app/vendor/glibc/string -I/app/vendor/glibc/time -I/app/vendor/gsl/include"
-export PKG_LDFLAGS=$LDFLAGS
-export PKG_CPPFLAGS=$CPPFLAGS
-
-export R_HOME=$R_BASE/lib64/R
-export R_INCLUDE=$R_HOME/include
-
-# copy over environment
-mkdir -p $BUILD_DIR/.profile.d
-cp "$BUILDPACK_DIR/bin/r_environment.sh" $BUILD_DIR/.profile.d/r_environment.sh
-
-# prevent warnings when building packages
-mkdir -p /app/vendor/R/lib64/R/doc/html
-touch /app/vendor/R/lib64/R/doc/html/R.css
-
-# install dependencies from CRAN
-echo "Executing init.r script" | indent
-
-# set the CRAN mirror and run the init.r program
-/app/vendor/R/bin/R -s <<RPROG > indent
-  Sys.setenv(BUILD_DIR="$BUILD_DIR")
-  setwd("$BUILD_DIR")
-  r <- getOption("repos");
-  r["CRAN"] <- "$CRAN_MIRROR";
-  options(repos=r);
-  `cat $BUILD_DIR/init.r`
-RPROG
-
-echo "R $R_VERSION successfully installed" | indent
-
-# need to copy binaries back so that any installed packages are included in the slug
-cp -R /app/vendor/R/* $VENDOR_DIR/R
